### ISSUE TITLE
SyntaxError: Unexpected token { in JSON

### ISSUE THREAD

**Issue by TimPaulaskasDS** [TimPaulaskasDS/sfparty#9]
Attempting to run `sfparty split` or `sfparty combine` results in an error.

```
undefined:7
	{
	^
SyntaxError: Unexpected token { in JSON at position 112
  at JSON.parse (<anonymous>)
  at getRootPath (file:///usr/local/lib/node_modules/@ds-sfdc/sfparty/src/index.js:622:32)
  at file:///usr/local/lib/node_modules/@ds-sfdc/sfparty/src/index.js:112:20
  at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

**Comment by TimPaulaskasDS** [comment]
The sfdx-project.json has the following content:
```
{
    "packageDirectories": [
        {
            "path": "force-app",
            "default": true
        }
	{
            "path": "my-package"
        }
    ],
    "namespace": "",
    "sfdcLoginUrl": "https://login.salesforce.com",
    "sourceApiVersion": "55.0"
}
```

It should be:
```
{
    "packageDirectories": [
        {
            "path": "force-app",
            "default": true
        },
	    {
            "path": "my-package"
        }
    ],
    "namespace": "",
    "sfdcLoginUrl": "https://login.salesforce.com/",
    "sourceApiVersion": "55.0"
}
```

**Comment by TimPaulaskasDS** [comment]
We should add some error handling if the sfdx-project.json doesn't load correctly; we can report an issue with the file and exit gracefully.
